{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Queen Attack\n",
    "\n",
    "Given the position of two queens on a chess board, indicate whether or not they\n",
    "are positioned so that they can attack each other.\n",
    "\n",
    "In the game of chess, a queen can attack pieces which are on the same\n",
    "row, column, or diagonal.\n",
    "\n",
    "A chessboard can be represented by an 8 by 8 array.\n",
    "\n",
    "So if you're told the white queen is at (2, 3) and the black queen at\n",
    "(5, 6), then you'd know you've got a set-up like so:\n",
    "\n",
    "```text\n",
    "_ _ _ _ _ _ _ _\n",
    "_ _ _ _ _ _ _ _\n",
    "_ _ _ W _ _ _ _\n",
    "_ _ _ _ _ _ _ _\n",
    "_ _ _ _ _ _ _ _\n",
    "_ _ _ _ _ _ B _\n",
    "_ _ _ _ _ _ _ _\n",
    "_ _ _ _ _ _ _ _\n",
    "```\n",
    "\n",
    "You'd also be able to answer whether the queens can attack each other.\n",
    "In this case, that answer would be yes, they can, because both pieces\n",
    "share a diagonal.\n",
    "\n",
    "## Exception messages\n",
    "\n",
    "Sometimes it is necessary to raise an exception. When you do this, you should include a meaningful error message to\n",
    "indicate what the source of the error is. This makes your code more readable and helps significantly with debugging. Not\n",
    "every exercise will require you to raise an exception, but for those that do, the tests will only pass if you include\n",
    "a message.\n",
    "\n",
    "To raise a message with an exception, just write it as an argument to the exception type. For example, instead of\n",
    "`raise Exception`, you shold write:\n",
    "\n",
    "```python\n",
    "raise Exception(\"Meaningful message indicating the source of the error\")\n",
    "```\n",
    "\n",
    "## Submitting Exercises\n",
    "\n",
    "Note that, when trying to submit an exercise, make sure the solution is in the `$EXERCISM_WORKSPACE/python/queen-attack` directory.\n",
    "\n",
    "You can find your Exercism workspace by running `exercism debug` and looking for the line that starts with `Workspace`.\n",
    "\n",
    "For more detailed information about running tests, code style and linting,\n",
    "please see the [help page](http://exercism.io/languages/python).\n",
    "\n",
    "## Source\n",
    "\n",
    "J Dalbey's Programming Practice problems [http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html](http://users.csc.calpoly.edu/~jdalbey/103/Projects/ProgrammingPractice.html)\n",
    "\n",
    "## Submitting Incomplete Solutions\n",
    "It's possible to submit an incomplete solution so you can see how others have completed the exercise.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def board(white_position, black_position):\n",
    "    pass\n",
    "\n",
    "\n",
    "def can_attack(white_position, black_position):\n",
    "    pass\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "\n",
    "\n",
    "# Tests adapted from `problem-specifications//canonical-data.json` @ v2.0.0\n",
    "\n",
    "class QueenAttackTest(unittest.TestCase):\n",
    "\n",
    "    def test_queen_valid_position(self):\n",
    "        try:\n",
    "            board((1, 1), (2, 2))\n",
    "        except ValueError:\n",
    "            self.fail(\"Unexpected Exception\")\n",
    "\n",
    "    def test_queen_negative_row(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            board((1, 1), (-2, 2))\n",
    "\n",
    "    def test_queen_invalid_row(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            board((1, 1), (8, 4))\n",
    "\n",
    "    def test_queen_negative_column(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            board((1, 1), (2, -2))\n",
    "\n",
    "    def test_queen_invalid_column(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            board((1, 1), (4, 8))\n",
    "\n",
    "    def test_attack_false(self):\n",
    "        self.assertIs(can_attack((2, 4), (6, 6)), False)\n",
    "\n",
    "    def test_attack_same_row(self):\n",
    "        self.assertIs(can_attack((2, 4), (2, 6)), True)\n",
    "\n",
    "    def test_attack_same_column(self):\n",
    "        self.assertIs(can_attack((4, 5), (2, 5)), True)\n",
    "\n",
    "    def test_attack_diagonal1(self):\n",
    "        self.assertIs(can_attack((2, 2), (0, 4)), True)\n",
    "\n",
    "    def test_attack_diagonal2(self):\n",
    "        self.assertIs(can_attack((2, 2), (3, 1)), True)\n",
    "\n",
    "    def test_attack_diagonal3(self):\n",
    "        self.assertIs(can_attack((2, 2), (1, 1)), True)\n",
    "\n",
    "    def test_attack_diagonal4(self):\n",
    "        self.assertIs(can_attack((2, 2), (5, 5)), True)\n",
    "\n",
    "    # Tests beyond this point are not part of the canonical data.\n",
    "\n",
    "    # If either board or can_attack are called with an invalid board position\n",
    "    # they should raise a ValueError with a meaningful error message.\n",
    "    def test_invalid_position_can_attack(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            can_attack((0, 0), (7, 8))\n",
    "\n",
    "    def test_queens_same_position_board(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            board((2, 2), (2, 2))\n",
    "\n",
    "    def test_queens_same_position_can_attack(self):\n",
    "        with self.assertRaisesWithMessage(ValueError):\n",
    "            can_attack((2, 2), (2, 2))\n",
    "\n",
    "    def test_board1(self):\n",
    "        ans = ['________',\n",
    "               '________',\n",
    "               '___W____',\n",
    "               '________',\n",
    "               '________',\n",
    "               '______B_',\n",
    "               '________',\n",
    "               '________']\n",
    "        self.assertEqual(board((2, 3), (5, 6)), ans)\n",
    "\n",
    "    def test_board2(self):\n",
    "        ans = ['______W_',\n",
    "               '_______B',\n",
    "               '________',\n",
    "               '________',\n",
    "               '________',\n",
    "               '________',\n",
    "               '________',\n",
    "               '________']\n",
    "        self.assertEqual(board((0, 6), (1, 7)), ans)\n",
    "\n",
    "    # Utility functions\n",
    "    def setUp(self):\n",
    "        try:\n",
    "            self.assertRaisesRegex\n",
    "        except AttributeError:\n",
    "            self.assertRaisesRegex = self.assertRaisesRegexp\n",
    "\n",
    "    def assertRaisesWithMessage(self, exception):\n",
    "        return self.assertRaisesRegex(exception, r\".+\")\n",
    "\n",
    "\n",
    "unittest.main(argv=[''], exit=False)\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 2
}
